apiVersion: v1
kind: Secret
metadata:
  name: weather-api-key
  namespace: dev-namespace
  labels:
    group: weather-app
type: Opaque
stringData:
  WEATHER_API_KEY: "sk-lab-DO-NOT-USE-IN-PROD-1234567890"
